### PR TITLE
proxy support

### PR DESCRIPTION
**Pull request by purinda**
- Modified html_client to support proxy configuration 
- Modified tests to support urllib3

### CODE REVIEW

**Comment by kn** [comment]
Thanks for the PR! It looks like it's not so common to support proxy with API client library. Do you mind explaining your usecase?

**Comment by purinda** [comment]
Thanks for the feedback! We (my team) uses the library for reporting project deployment activity and continuous integration notifications to our Slack account. So I started using your library to interface with our python scripts.

The organisation I work for has a proxy for outgoing traffic so I integrated pyslack library with our scripts and configured scripts to use the proxy settings. So I thought I should modify the library to work with/without a proxy as it solves our problems of getting through the proxy.

We also have a more complicated proxy configuration for production servers where we use pyslack to report mission critical messages to the developer channel. And the changes in this PR fixes the problem of getting though complicated proxy configurations.

Cheers.

**Comment by kn** [comment]
Sorry for the delay in response and thanks for the detailed explanation!

It looks like `requests` library that we currently use [supports proxies](http://www.python-requests.org/en/latest/user/advanced/#proxies) also. Do you mind using it instead?

**Comment by hallkk** [comment]
waiting for code merge

**Pull request closed without merging**
